version: "3.9"

services:
  backend:
    build: ./backend
    command: python tp22_project/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    restart: unless-stopped